### ISSUE TITLE
DAO token should be optional

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#127]
Currently, the user is forced to give their DAO a token name and symbol. However, most DAOs don't use their internal token (e.g. genDAO, polkaDAO, dxDAO, dOrg)

Adding a token should be optional, and it should not be on the first screen. I am not sure about the best way to adjust the views to accommodate this flow, but we should discuss.

**Comment by oshimony** [comment]
Research whether or not there is a quick fix here. forgeOrg in [DAOcreator.sol](https://github.com/daostack/arc/blob/master/contracts/universalSchemes/DaoCreator.sol) forces user to choose a token name and symbol.) R

**Comment by orishim** [comment]
One way to achieve a 'no token' option is by 
- enforcing 0 tokens to all founders
-  setting the token to some standard null value: tokenName: '000', tokenSymbol: '000'

**Comment by orishim** [comment]
Or by asking the user to specify an abbreviation for the org and then setting that as the tokenName and tokenSymbol and setting supply to 0.

Creating and allocating the token to founders should be an 'advanced' option.

**Comment by dOrgJelli** [comment]
**@mrrobot16 asks:**
"what happens if at the time of creating a contract/dao if the users does not assign TokenName Symbol or TokenHolders. Can user later modify that? I am trying to think if this is a javascript problem or it goes all the way to the contract?"

**Response:**
The DAOToken contract still must be deployed as the Avatar requires it upon construction, so even though in the UI we're saying "no token", we're still deploying one. Now what should we do if the user has said they don't want one? Here's a suggestion from Ori for how to initialize the DAOToken: https://github.com/dOrgTech/DAOcreator/issues/127#issuecomment-500595768

Also here's the contracts referenced above for further clarity:
"Avatar requires a DAOToken upon construction...": https://github.com/daostack/arc/blob/9ac194fa8ad3acdea2199388ddde614229c08ef5/contracts/controller/Avatar.sol#L32

DAOToken: https://github.com/daostack/arc/blob/master/contracts/controller/DAOToken.sol

**Comment by mrrobot16** [comment]
ok i see now, ```setting the token to some standard null value: tokenName: '000', tokenSymbol: '000'```.  Where (What step) would the user be able to define no token?

**Comment by mrrobot16** [comment]
what exact standard value can we use? Is it relevant?, And pretty much members in MembersStep would all have 0 tokens, but we still capture addresses etc? Correct?

**Comment by dOrgJelli** [comment]
Thinking about this more, I think we shouldn't go the route of making the DAOToken unusable by setting it's name to '000' and it's quantity to zero like @orishim suggests. Reasons is, once this is done, there's no way to go back.

A better solution (which @orishim has talked about in the past) is to just hide the concept of the DAO's token from the user. Instead of asking the user to give a "Token Name" and "Token Symbol" in the setup step, we could instead just ask them for a "DAO Symbol" to go along with the DAO's name.

To restate for clarity, currently we have the fields:
`DAOname, TokenName, TokenSymbol`

and we would instead change it in the UI to be:
`DAOname, DAOsymbol`

In the backend you'd still have the 3 properties of the DAO, and DAOname would be used for both DAOname and TokenName. DAOsymbol === TokenSymbol.

This way we hide from the user the concept of an ERC20 the DAO owns (which is confusing), and just ask them to specify a <=4 character symbol for their DAO.

Does this make sense?

**Comment by mrrobot16** [comment]
This also means that in membersEditor we should have the tokens forms. But just capture the address and assign how much rep each member will have?

**Comment by dOrgJelli** [comment]
This is a good point. I think that in the MembersEditor, we should have an option that says "Distribute DAO tokens to members?". This way by default they only have to worry about REP, but can opt into distributing tokens too if they want to. We should have extra explination of what this actually is if they click on it or something like that.

It looks like the bulk of this work will be refactoring how the MembersEditor introduces the tokens to the user.

**Comment by dOrgJelli** [comment]
Correction ^^^ MembersStep, I don't think this logic should be in the MembersEditor as it should remain a generic editor for the members array. It should only be modified to now take in a boolean that says "show tokens".

**Comment by mrrobot16** [comment]
Shows tokens input means it should be how it current is right?

No shows tokens input means its in 'No token mode'?

**Comment by dOrgJelli** [comment]
yes that's correct.

**Comment by mrrobot16** [comment]
its means also to set token default = 0.

**Comment by dOrgJelli** [comment]
You don't have to worry about this, as the underlying form should do this for you. You may have to update the forms lib to do this though for the token field.

**Comment by mrrobot16** [comment]
ok. Where is user gonna be ask if no token? In Step 1 correct?
If no token set, then hide tokens field for members and set tokens for each member to 0?

**Comment by dOrgJelli** [comment]
Nonono, in the naming step all we're doing is changing the 3 fields to be 2 (DAO Name, DAO Symbol), and in the members step we're adding an option to "distribute / allocate tokens".

**Comment by mrrobot16** [comment]
Ok great!

**Comment by dOrgJelli** [comment]
Fixed in V2
