### ISSUE TITLE
'Voting Configuration' always shows as 'Custom'

### ISSUE THREAD

**Issue by orishim** [dOrgTech/DAOcreator#211]
No matter which preset you choose (Easy, Normal, Critical) the selected one is always displayed as custom.

The configuration still changes accordingly, the selection bar just doesn't update properly.

**Comment by mrrobot16** [comment]
The reason why it always displays 'Custom' is because whenever user selects a config(Easy, Normal, Critical) its not setting properly form.preset. 

https://github.com/dOrgTech/DAOcreator/blob/d9efd7ee344194c0465317d08d00444cb4566673/src/components/common/dao/GenesisProtocolPresetEditor.tsx#L96

In fact form.preset it always returns undefined even after users selects a different config.
[https://github.com/dOrgTech/DAOcreator/blob/d9efd7ee344194c0465317d08d00444cb4566673/src/components/common/dao/GenesisProtocolPresetEditor.tsx#L55](https://github.com/dOrgTech/DAOcreator/blob/d9efd7ee344194c0465317d08d00444cb4566673/src/components/common/dao/GenesisProtocolPresetEditor.tsx#L55)

I think i have a solution on a FormLevel for it to display the proper config selected, but I am not sure if it affects the config from a StateLevel. I am gonna give it a try.

**Comment by mrrobot16** [comment]
Fix is in PR: https://github.com/dOrgTech/DAOcreator/pull/218
