### ISSUE TITLE
Cotary Create: Feedback January 31st -  Build Deployed live at https://daocreator-v2.herokuapp.com/

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#352]
Please write down all feedback that you can come for https://daocreator-v2.herokuapp.com/

Thanks :)

**Comment by dOrgJelli** [comment]
- I don't like having to log into Metamask when the dApp opens. I feel it should happen when it's first needed. For example, when the users gets to the Members step, have a button for "Connect Wallet", and then once a wallet is connected change that button to "Add Self" or something like that which populates the member field with your address.
- Step 1's overview doesn't show the DAO symbol, and only shows the DAO's name. Also should the overview entries have a field label? Currently it only shows the value the user input.
- In step 3, when you click the "edit" icon, it should switch to a check mark to let the user know that if they press it again their changes will be set.
- In step 3, if you click edit on an address, then click delete, when you add an address again it's still in an edit mode. The edit mode should be reset.
- In step 3, when you click the "edit" icon, there's no way to exit the edit mode and persist your old values. For example, if I click edit then set my REP to 12, and I want to discard these changes, there's no way to do so. Maybe change the delete icon in the edit mode to a cancel icon that takes you out of edit mode and sets back the old value.
- In step 3, when you click "edit", the layout of all member's REP columns changes. You'd expect the layout to stay the same and just have the text field take up the same space that it did before.
- In step 3, if you enable "Distribute tokens", set some token amount, then disable "Distribute tokens", we should ensure the final output has all tokens set to zero. Currently these amounts are kept in the state.
- Switching networks causes the app to reset because metamask reloads the page. This causes all progress to be lost! We should store the DAOs state in localstorage when the page exits (see V1 UI for an example of this). We should then ask the user when the app restarts "Do you want to continue from where you left off?" and give them an overview of what their DAO looks like. See V1 to see this in action.
- In step 2, when you click on "Advanced Configuration", Contribution Reward and Scheme Registrar are disabled? Why is this, since they're apart of the default configuration of the DAO.
- If the user disables the Scheme Registrar, we should have a warning letting them know that their DAO will not be able to modify and upgrade itself in the future. This warning should be in the Advanced Configuration view, and also in the final deployment view as this is a major thing users should be aware of.
- When the user begins installation / deployment, all "edit" icons for previous steps should be disabled.
- Advanced configuration values are not persisted. I went in and edited the configuration of my Contribution Reward scheme to have 26 days instead of 30 days, and it was not reflected in my deployment.
- After deployment finishes, we should (1) have an option for users to copy their DAO addresses (see V1 for an example of this), and we should (2) let the user know that they must copy the alchemy URL for their DAO and save it somewhere because it won't be discoverable in Alchemy. If they loose their Avatar address they will not be able to visit their DAO again (unless they sift for it in their transaction history).
- When the user exits the app during deployment, they should be given a popup warning letting them know that all progress will be lost.
- In the deployment step, we should warn users that if they use "speed up transaction" feature in metamask and other wallets, that deployment will be broken (see V1 for an example of this).

**Comment by orishim** [comment]
We should add a DAOstack logo somewhere in the U.I., the user should know that they are using DAOstack

**Comment by orishim** [comment]
- Advanced view is totally misaligned

- `Proposing Rep Reward` is missing from Advanced

- All three toggles in step 2 should default to ON.

- Is the Configure step 2 functional at all??? Clicking "Slow", "Medium" and "Fast" does not change any values when I click advanced to check. Neither does anything change in advanced when I press the toggles.

Here is what the values should be for each:

| SPEED | Queued (Funding & Voting Power) | Pre-Boosted (Funding & Voting Power) | Boosted (Funding & Voting Power) | Quiet Ending (Funding & Voting Power) | Queued (Plugin Manager) | Pre-Boosted (Plugin Manager) | Boosted (Plugin Manager) | Quiet Ending (Plugin Manager) |
|-|-|-|-|-|-|-|-|-|
| Slow | 30 days | 1 day 12 hrs | 3 days | 2 days | 60 days | 3 days | 6 days | 4 days |
| Medium | 7 days | 12 hrs | 1 day | 16 hrs | 30 days | 1 day 12 hrs | 3 days | 2 days |
| Fast | 7 days | 12 hrs | 1 day | 16 hrs | 7 days | 12 hrs | 1 day | 16 hrs |

If `Reward successful proposers` is off, set `Proposing Rep Reward` to 0
If `Reward correct voters and penalize incorrect voters` is off, set `Voter Reputation Loss` to 0
If `Auto-incentivize proposal curation` is off, set `Minimum DAO Bounty` & `DAO Bounty Const` to 0 

@dOrgJelli please double check me on these values

**Comment by mrrobot16** [comment]
I have created issues for the above comments.

**Comment by Flash-Git** [comment]
Everything that isn't related to the advanced config on step 2 and the state loading has been handled.
Cesar is working on the former and I'm going to take the latter tomorrow.
