### ISSUE TITLE
xDAI support for DAOcreator

### ISSUE THREAD

**Issue by Theylon** [dOrgTech/DAOcreator#387]

**Comment by dOrgJelli** [comment]
Two possible paths forward:
1. Deploy a v33 deployment of Arc's base contracts to XDAI. DAOcreator would then just have to be updated to use the latest `migration.json` addresses.
2. Disable Generic Scheme within DAOcreator, as Arc deployments post v33 don't have UGenericScheme. If we left Generic Scheme enabled, it'd mean the newly deployed DAO would have to add the new Generic Scheme address to the subgraph in order to use it within Alchemy.

**Comment by dOrgJelli** [comment]
^^^ this is all assuming we're doing this in the absence of Arc Hives / Factories, which aren't live yet.

**Comment by orenyodfat** [comment]
@dOrgJelli what the status of that ?

**Comment by dOrgJelli** [comment]
@orenyodfat, @cbrzn has been pushing this forward, and I believe it should be PR'd into Alchemy shortly.

**Comment by cbrzn** [comment]
https://github.com/daostack/alchemy/pull/1791
