### ISSUE TITLE
Cotary Create: Minimum DAO Bounty cannot be set to 0

### ISSUE THREAD

**Issue by Flash-Git** [dOrgTech/DAOcreator#414]
["If Auto-incentivize proposal curation is off, set Minimum DAO Bounty & DAO Bounty Const to 0"
](https://github.com/dOrgTech/DAOcreator/issues/352#issuecomment-582132048)
`DAO Bounty Const` isn't being set with this setting and according to the [contract](https://github.com/daostack/infra/blob/a09e9a524fbacc9fb39d5d1de8986dcf45c4889c/contracts/votingMachines/GenesisProtocolLogic.sol#L259-L264) both `Minimum DAO Bounty` and `DAO Bounty Const` cannot be set to 0.

**Comment by dOrgJelli** [comment]
I've created issues for this in the repo, but haven't heard a response:
https://github.com/daostack/infra/issues/76
https://github.com/daostack/infra/issues/75

I think we should make the change ourselves and PR it in... until then we should enforce this in the form library :/ we can set it to 1 instead of 0
