### ISSUE TITLE
During Scheme setup separate UniversalSchemes from Schemes

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/DAOcreator#93]
**Thought:** The user should have a good understanding of what schemes are "service" contract (universal), and what schemes are "instance" contracts (normal schemes). That way they know the instances will be deployed specifically for their organization.

Think we should make the separation within the UI?

**Comment by sogasg** [comment]
In the current version, we only have universal schemes.

**My thoughts**: I don’t think we should have any separation in the UI. Maybe we could have a notice about it, but I don’t think the user really needs to know anything about that.
I don’t think the user should even need to know anything about Ethereum, blockchain or smart contracts to use this. Therefore I believe low-level details like this might just confuse the user.

I think we really need to define the target audience in order to figure things like this 😛
